* Asymptotic normality in performative prediction

This repository is a supplement for "Asymptotic normality in performative prediction" by Joshua Cutler, Mateo Diaz, and Dmitriy Drusvyatskiy.

** One-time setup

*The instructions assume that your current working directory is the base of this repository.*

The code in this repository is written in Julia. To set the environment install Julia 1.7.1 from https://julialang.org/downloads/ and make sure =julia= is available in your =PATH=.

Instantiate the Julia packages
#+begin_src
$ julia --project=. -e "import Pkg; Pkg.instantiate()"
#+end_src

** Running

To generate the deviation samples execute
#+begin_src
$ julia --threads 4 --project=. main.jl
#+end_src
You can modify the number of threads to make further use of your processor.

*Warning*: running this command might take a while. We included the run we generated for the paper in the repository under the name =results.jld2=.

To draw the contour plots in Figure 1 of the paper run
#+begin_src
$ julia --project=. print_kde.jl
#+end_src

*** Random seed
We fixed the random seeds for the reproducibility of the experiments. In case you want to change it, look for the line
#+begin_src julia
Random.seed!(2526)
#+end_src
in both =main.jl= (line 20) and =print_kde.jl= (line 9) and change the input.
